GUIDELINES = {
    "ontonotes_person": {"en": ["People, including fictional."]},
    "ontonotes_norp": {"en": ["Nationalities or religious or political groups."]},
    "ontonotes_facility": {"en": ["Buildings, airports, highways, bridges, etc."]},
    "ontonotes_organization": {"en": ["Companies, agencies, institutions, etc."]},
    "ontonotes_gpe": {"en": ["Countries, cities, states."]},
    "ontonotes_location": {"en": ["Non-GPE locations, mountain ranges, bodies of water."]},
    "ontonotes_product": {"en": ["Objects, vehicles, foods, etc. (Not services)."]},
    "ontonotes_event": {"en": ["Named hurricanes, battles, wars, sports events, etc."]},
    "ontonotes_work_of_art": {"en": ["Titles of books, songs, etc."]},
    "ontonotes_law": {"en": ["Named documents made into laws."]},
    "ontonotes_language": {"en": ["Any named language."]},
    "ontonotes_date": {"en": ["Absolute or relative dates or periods."]},
    "ontonotes_time": {"en": ["Times smaller than a day."]},
    "ontonotes_percent": {"en": ["Percentage, including ”%“."]},
    "ontonotes_money": {"en": ["Monetary values, including unit."]},
    "ontonotes_quantity": {"en": ["Measurements, as of weight or distance."]},
    "ontonotes_ordinal": {"en": ["first, second, third, First, fourth, fifth, Second, seventh, eighth, sixth."]},
    "ontonotes_cardinal": {"en": ["two, one, three, One, four, five, six, seven, Two, half."]},
}
