#Training args
model_name_or_path: meta-llama/Meta-Llama-3.1-8B
torch_dtype: bfloat16
use_lora: true
quantization: 4
quantization_inference: null
bf16_full_eval: true
gradient_checkpointing: true
force_auto_device_map: false
use_flash_attention: true
deepspeed: configs/deepspeed_configs/deepspeed_zero3.json

# dataset arguments
dataset_dir:
  /sorgin1/users/neildlf/GoLLIE-dev/data/pretraining_data_processed_w_examples
train_tasks:
  - gollie_pretrain_data.ie
validation_tasks:
  - gollie_pretrain_data.ie
test_tasks:
  - gollie_pretrain_data.ie

max_examples_per_task_train: 30000
max_examples_per_task_val: 5000
max_examples_per_task_test: null
max_seq_length: 8192
generation_max_length: 8192
ignore_pad_token_for_loss: true
prompt_loss_weight: 0.0

# checkpoint settings
output_dir: /sorgin1/users/neildlf/GoLLIE-dev/model/GoLLIE+-8b_Llama3_BS128_R128_pretrain
overwrite_output_dir: true
load_best_model_at_end: false
save_strategy: "epoch"
save_steps: 1000
save_total_limit: 999

# evaluation
do_train: true
do_eval: true
do_predict: true
eval_strategy: "epoch"
eval_steps: 500
eval_delay: 0
predict_with_generate: true
evaluate_all_checkpoints: true

# batch size
per_device_train_batch_size: 2 #4 #16
per_device_eval_batch_size: 2 #2 #8
gradient_accumulation_steps: 2
generation_num_beams: 1

# optimizer settings
#optim: adamw_torch_fused
optim: adamw_hf
learning_rate: 0.0003
weight_decay: 0.001
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.1
adam_epsilon: 0.0000001

# lora settings
lora_r: 128
lora_alpha: 256
lora_dropout: 0.05
lora_target_modules:
  - all

# reporting
logging_strategy: steps
logging_first_step: true
logging_steps: 25
report_to: wandb
run_name: "GoLLIE-8b_Llama3_BS128_R128_pretrain"
disable_tqdm: false

# hub settings
push_to_hub: false
resume_from_checkpoint: false

# performance
bf16: true
fp16: false
torch_compile: false
ddp_find_unused_parameters: false
